# Generated by Django 2.0.7 on 2021-06-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, null=True)),
                ('thumb', models.CharField(blank=True, max_length=120, null=True)),
                ('link', models.CharField(max_length=120)),
                ('published', models.DateField()),
                ('origin', models.CharField(max_length=20)),
            ],
        ),
    ]
