# Generated by Django 2.0.7 on 2021-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='original_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
