# Generated by Django 2.0.7 on 2021-06-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_rss', '0002_posts_original_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('youtube_id', models.CharField(max_length=30)),
                ('twitter_id', models.CharField(max_length=30)),
                ('instagram_id', models.CharField(max_length=30)),
                ('facebook_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='social_rss.Users'),
            preserve_default=False,
        ),
    ]
