# Generated by Django 2.0.7 on 2021-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_rss', '0003_auto_20210607_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
